# build stage w/ maven
FROM maven:3.9-eclipse-temurin-24-alpine AS build

WORKDIR /app

# copying and downloading dependencies
COPY pom.xml .
RUN mvn dependency:go-offline

# copy source code and build
COPY src ./src
RUN mvn clean package -DskipTests

# runtime stage
FROM eclipse-temurin:24-jre-alpine

WORKDIR /app

# copy only JAR from build stage
COPY --from=build /app/target/snug-0.0.1-SNAPSHOT.jar app.jar

# run app
CMD ["java", "-jar", "app.jar"]

EXPOSE 8080
